{
    'name': 'AFR ECM — Enterprise Content Management',
    'version': '16.0.1.5.0',
    'category': 'Document Management',
    'summary': 'ECM sobre OCA dms: tipos de documento, metadados, confidencialidade, audit log e acervo físico com QR',
    'author': 'Engenapp',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'mail',
        'web',
        'dms',
        'dms_user_role',
        'hr_dms_field',
        'queue_job',
        'queue_job_cron_jobrunner',
    ],
    'data': [
        'security/security.xml',
        'security/security_ecm_areas.xml',
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'security/record_rules_ecm_areas.xml',
        'security/record_rules_nc_capa.xml',
        'data/document_type_data.xml',
        'data/mail_activity_data.xml',
        'data/cron_data.xml',
        'data/dms_access_group_data.xml',
        'data/dms_access_group_links.xml',
        'data/cron_license_renewal.xml',
        'data/cron_ti_revocation.xml',
        'data/sequence_nc_capa.xml',
        'data/cron_capa_verification.xml',
        'reports/location_label_template.xml',
        'reports/location_label_report.xml',
        'views/document_type_views.xml',
        'views/physical_location_views.xml',
        'views/audit_log_views.xml',
        'views/dms_file_views.xml',
        'views/dms_directory_views.xml',
        'views/nc_views.xml',
        'views/capa_views.xml',
        'views/menus_nc_capa.xml',
        'views/menus.xml',
    ],
    'external_dependencies': {
        'python': ['qrcode', 'pytesseract', 'pdf2image', 'PIL'],
        'bin': ['tesseract', 'pdftotext'],
    },
    'installable': True,
    'application': True,
}
