from . import test_audit_log
from . import test_physical_location
from . import test_document_type
from . import test_approval
from . import test_expiration
from . import test_ocr
from . import test_ti_revocation
from . import test_record_rules_refinement
from . import test_audit_scope_tree_rule
