# -*- coding: utf-8 -*-
"""Tests for F4.3.6 — NOTIVISA (afr.ecm.notivisa) workflow model.

Mirrors the test_nc_capa.py pattern: tagged TransactionCase, pytest collects
without an Odoo env (file must import cleanly, all Odoo state lives inside
test methods / setUpClass under TransactionCase).

Test cases:
1. test_sequence_assigned           — name assigned via ir.sequence
2. test_full_happy_path             — all states nominal flow (no death)
3. test_death_severity_constraint   — cannot close without notivisa_protocol
4. test_notivisa_protocol_required  — analysis→notified requires protocol+date
5. test_capa_helper_creates_link    — action_open_capa creates capa and links
6. test_cron_overdue_escalation     — overdue detection fires activity
7. test_cancel_flow_manager_only    — cancel requires manager + reason
"""
from datetime import timedelta

from odoo.exceptions import UserError, ValidationError
from odoo.tests.common import TransactionCase, new_test_user, tagged


@tagged("post_install", "-at_install", "afr_ecm", "afr_ecm_notivisa")
class TestNotivisa(TransactionCase):

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.Notivisa = cls.env["afr.ecm.notivisa"]
        cls.Capa = cls.env["afr.ecm.capa"]

        cls.regulatorio_user = new_test_user(
            cls.env,
            login="reg_user_notivisa_test",
            groups="afr_ecm.group_ecm_area_regulatorio",
        )
        cls.manager = new_test_user(
            cls.env,
            login="ecm_mgr_notivisa_test",
            groups="afr_ecm.group_ecm_manager",
        )
        cls.plain_user = new_test_user(
            cls.env,
            login="ecm_plain_notivisa_test",
            groups="afr_ecm.group_ecm_user",
        )

    # ------------------------------------------------------------------ #
    #  Helpers                                                             #
    # ------------------------------------------------------------------ #
    def _make_notivisa(self, **kwargs):
        vals = {
            "title": "Evento Adverso de Teste",
            "event_type": "adverse_event",
            "severity": "medium",
            "responsible_id": self.regulatorio_user.id,
        }
        vals.update(kwargs)
        return self.Notivisa.create(vals)

    def _advance_to_analysis(self, rec):
        rec.action_start_analysis()
        return rec

    def _advance_to_notified(self, rec):
        self._advance_to_analysis(rec)
        rec.write({
            "notivisa_protocol": "ANVISA-2025-001234",
            "notivisa_submission_date": "2026-05-13 10:00:00",
        })
        rec.action_record_notification()
        return rec

    def _advance_to_investigation(self, rec):
        self._advance_to_notified(rec)
        rec.action_start_investigation()
        return rec

    def _advance_to_corrective(self, rec):
        self._advance_to_investigation(rec)
        rec.write({"investigation_text": "<p>Causa: falha de embalagem.</p>"})
        rec.action_record_corrective_action()
        return rec

    # ------------------------------------------------------------------ #
    #  Test 1: sequence                                                    #
    # ------------------------------------------------------------------ #
    def test_sequence_assigned(self):
        """Name must be generated by ir.sequence as NOTIVISA/YYYY/NNNN."""
        rec = self._make_notivisa()
        self.assertTrue(rec.name, "name deve ser preenchido pela sequência")
        self.assertNotEqual(rec.name, "Novo")
        self.assertTrue(
            rec.name.startswith("NOTIVISA/"),
            f"Esperado prefixo 'NOTIVISA/', obtido: {rec.name}",
        )

    # ------------------------------------------------------------------ #
    #  Test 2: full happy path                                             #
    # ------------------------------------------------------------------ #
    def test_full_happy_path(self):
        """Full lifecycle from draft to closed without death severity."""
        rec = self._make_notivisa(severity="high")
        self.assertEqual(rec.state, "draft")

        # draft → analysis
        rec.action_start_analysis()
        self.assertEqual(rec.state, "analysis")
        self.assertIsNotNone(rec.state_entered_date, "state_entered_date deve ser setado")
        self.assertIsNotNone(rec.analysis_deadline, "analysis_deadline deve ser setado")

        # analysis → notified
        rec.write({
            "notivisa_protocol": "ANVISA-2025-TEST01",
            "notivisa_submission_date": "2026-05-13 09:00:00",
        })
        rec.action_record_notification()
        self.assertEqual(rec.state, "notified")
        self.assertIsNotNone(rec.notified_deadline)

        # notified → under_investigation
        rec.action_start_investigation()
        self.assertEqual(rec.state, "under_investigation")
        self.assertIsNotNone(rec.investigation_deadline)

        # under_investigation → corrective_action
        rec.write({"investigation_text": "<p>Causa identificada: falha de selagem.</p>"})
        rec.action_record_corrective_action()
        self.assertEqual(rec.state, "corrective_action")
        self.assertIsNotNone(rec.corrective_deadline)
        self.assertIsNotNone(rec.investigation_date)

        # corrective_action → closed
        rec.write({
            "closure_summary": "<p>Ação corretiva implementada com sucesso.</p>",
            "closure_outcome": "resolved",
        })
        rec.action_close()
        self.assertEqual(rec.state, "closed")
        self.assertIsNotNone(rec.closure_date)

    # ------------------------------------------------------------------ #
    #  Test 3: death severity constraint                                   #
    # ------------------------------------------------------------------ #
    def test_death_severity_constraint(self):
        """Severity=death cannot be closed without notivisa_protocol."""
        rec = self._make_notivisa(severity="death")
        self._advance_to_corrective(rec)

        rec.write({
            "closure_summary": "<p>Sumário obrigatório.</p>",
            "closure_outcome": "resolved",
            # notivisa_protocol was set in _advance_to_notified, but let's clear it.
        })
        # Clear the protocol to test the gate.
        rec.write({"notivisa_protocol": False})

        with self.assertRaises(UserError):
            rec.action_close()

        # Now also check the DB-level constraint.
        with self.assertRaises((UserError, ValidationError)):
            rec.write({"state": "closed"})

    # ------------------------------------------------------------------ #
    #  Test 4: notivisa_protocol required for "notified" state           #
    # ------------------------------------------------------------------ #
    def test_notivisa_protocol_required(self):
        """action_record_notification must fail without protocol or submission date."""
        rec = self._make_notivisa()
        self._advance_to_analysis(rec)

        # Missing both fields.
        with self.assertRaises(UserError):
            rec.action_record_notification()

        # Only protocol, no date.
        rec.write({"notivisa_protocol": "ANVISA-TEST-999"})
        with self.assertRaises(UserError):
            rec.action_record_notification()

        # Both provided — should work.
        rec.write({"notivisa_submission_date": "2026-05-13 12:00:00"})
        rec.action_record_notification()
        self.assertEqual(rec.state, "notified")

    # ------------------------------------------------------------------ #
    #  Test 5: CAPA helper creates and links CAPA                        #
    # ------------------------------------------------------------------ #
    def test_capa_helper_creates_link(self):
        """action_open_capa must create afr.ecm.capa and set corrective_action_capa_id."""
        rec = self._make_notivisa()
        self._advance_to_corrective(rec)

        self.assertFalse(rec.corrective_action_capa_id)
        rec.action_open_capa()

        self.assertTrue(rec.corrective_action_capa_id, "corrective_action_capa_id deve ser preenchido")
        capa = rec.corrective_action_capa_id
        self.assertEqual(capa.type, "corrective")
        self.assertIn(rec.name, capa.title or "", "Título da CAPA deve mencionar o NOTIVISA")

        # Second call should raise (already linked).
        with self.assertRaises(UserError):
            rec.action_open_capa()

    # ------------------------------------------------------------------ #
    #  Test 6: cron overdue escalation                                    #
    # ------------------------------------------------------------------ #
    def test_cron_overdue_escalation(self):
        """_cron_notivisa_overdue must detect overdue records and post activity."""
        rec = self._make_notivisa()
        self._advance_to_analysis(rec)

        # Backdate the analysis_deadline to yesterday to simulate SLA overdue.
        yesterday = fields_now = __import__("odoo").fields.Datetime.now() - timedelta(days=1)
        rec.write({"analysis_deadline": yesterday})

        initial_activity_count = len(rec.activity_ids)
        escalated = self.Notivisa._cron_notivisa_overdue()

        self.assertGreaterEqual(escalated, 1, "Cron deve retornar pelo menos 1 escalação")
        self.assertGreater(
            len(rec.activity_ids), initial_activity_count,
            "Deve haver nova atividade de escalação no registro",
        )
        # Escalation activity has "Escalação" in summary.
        escalation_activities = rec.activity_ids.filtered(
            lambda a: "Escalação" in (a.summary or "")
        )
        self.assertTrue(escalation_activities, "Atividade de escalação deve existir")

        # Second run should NOT add duplicate escalation.
        count_before = len(rec.activity_ids)
        self.Notivisa._cron_notivisa_overdue()
        self.assertEqual(
            len(rec.activity_ids), count_before,
            "Segunda execução do cron não deve duplicar atividade de escalação",
        )

    # ------------------------------------------------------------------ #
    #  Test 7: cancel flow manager-only                                   #
    # ------------------------------------------------------------------ #
    def test_cancel_flow_manager_only(self):
        """Cancel requires ECM manager group and cancel_reason."""
        rec = self._make_notivisa()
        self._advance_to_analysis(rec)

        # Plain user (non-manager) cannot cancel.
        with self.assertRaises(UserError):
            rec.with_user(self.plain_user).action_cancel()

        # Manager without cancel_reason cannot cancel.
        with self.assertRaises(UserError):
            rec.with_user(self.manager).action_cancel()

        # Manager with reason: succeeds.
        rec.write({"cancel_reason": "Evento não confirmado — duplicata de NOTIVISA/2026/0001."})
        rec.with_user(self.manager).action_cancel()
        self.assertEqual(rec.state, "cancelled")

        # Cannot cancel already-cancelled.
        with self.assertRaises(UserError):
            rec.with_user(self.manager).action_cancel()

    # ------------------------------------------------------------------ #
    #  Test 8: atomic state transitions                                   #
    # ------------------------------------------------------------------ #
    def test_atomic_state_transitions(self):
        """State transitions must be atomic (single write call with all fields)."""
        rec = self._make_notivisa()
        # start_analysis should set state, state_entered_date, analysis_deadline atomically.
        rec.action_start_analysis()
        # All three must be set — atomic write guarantee.
        self.assertEqual(rec.state, "analysis")
        self.assertIsNotNone(rec.state_entered_date)
        self.assertIsNotNone(rec.analysis_deadline)

    # ------------------------------------------------------------------ #
    #  Test 9: analysis→investigation skip for non-death                 #
    # ------------------------------------------------------------------ #
    def test_analysis_to_investigation_non_death(self):
        """Non-death severity can skip from analysis directly to under_investigation."""
        rec = self._make_notivisa(severity="high")
        self._advance_to_analysis(rec)

        # Should succeed: high severity does not require NOTIVISA protocol first.
        rec.action_start_investigation()
        self.assertEqual(rec.state, "under_investigation")

    # ------------------------------------------------------------------ #
    #  Test 10: analysis→investigation blocked for death                 #
    # ------------------------------------------------------------------ #
    def test_analysis_to_investigation_blocked_for_death(self):
        """Death severity cannot skip from analysis to investigation without ANVISA notification."""
        rec = self._make_notivisa(severity="death")
        self._advance_to_analysis(rec)

        # Should be blocked.
        with self.assertRaises(UserError):
            rec.action_start_investigation()
